# Generated by Django 3.2.12 on 2022-03-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=400)),
                ('project_link', models.CharField(max_length=400)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('project_description', models.CharField(max_length=4000)),
                ('date_posted', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.usersignup')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Userbio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=3000)),
                ('date_posted', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.usersignup')),
            ],
            options={
                'db_table': 'Userbio',
            },
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_count', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.projects')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.usersignup')),
            ],
        ),
    ]
