# Generated by Django 3.2.12 on 2022-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=200, unique=True)),
                ('added_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Newslatter',
            },
        ),
    ]
